Renvoyer une erreur "propre" lorsqu'un fichier de conf est vide ou manquant.
Test préalable, plutôt que laisser "sed" se planter comme un
malpropre.

diff --git a/anaconf/src/liste-rancid b/anaconf/src/liste-rancid
--- a/anaconf/src/liste-rancid
+++ b/anaconf/src/liste-rancid
@@ -15,6 +15,7 @@
 #   2004/06/08 : pda/jean : conception
 #   2008/07/07 : pda      : ajout hp
 #   2008/12/15 : jean     : ajout d'un motif des types d'équipement à ignorer
+#   2010/09/27 : pda      : traitement du cas où un fichier n'existe pas encore
 #
 
 if [ $# != 2 ]
@@ -47,20 +48,26 @@ IFS=":"
 grep ":up$" $DB | egrep -v "$IGNORE" |
     while read eq type up
     do
-	case "$type" in
-	    cisco)
-		model=`fetch_model_cisco "$DIR/$eq"`
-		;;
-	    hp)
-		model=`fetch_model_hp "$DIR/$eq"`
-		;;
-	    juniper)
-		model=`fetch_model_juniper "$DIR/$eq"`
-		;;
-	    *)
-		echo "Unsupported type '$type' for '$eq' in $DB" >&2
-		exit 1
-		;;
-	esac
-	echo "$eq $type $model"
+	f="$DIR/$eq"
+	if [ ! -s "$f" ]
+	then
+	    echo "Missing or empty configuration file for '$eq'" >&2
+	else
+	    case "$type" in
+		cisco)
+		    model=`fetch_model_cisco "$DIR/$eq"`
+		    ;;
+		hp)
+		    model=`fetch_model_hp "$DIR/$eq"`
+		    ;;
+		juniper)
+		    model=`fetch_model_juniper "$DIR/$eq"`
+		    ;;
+		*)
+		    echo "Unsupported type '$type' for '$eq' in $DB" >&2
+		    exit 1
+		    ;;
+	    esac
+	    echo "$eq $type $model"
+	fi
     done
